all: try-array

try-array: try-array.cu
	nvcc -o try-array try-array.cu

try-texture-compare: try-texture-compare.cu
	nvcc -o try-texture-compare try-texture-compare.cu

clean:
	rm -f try-texture-compare

